; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/54.03.20/platform-espressif32.zip
board = esp32-c6-devkitm-1
upload_protocol = esptool
framework = arduino
monitor_speed = 115200
monitor_filters = esp32_c6_usb_serial
monitor_port = /dev/serial/by-id/usb-Espressif_USB_JTAG_serial_debug_unit_58:E6:C5:19:1B:AC-if00

;monitor_filters = direct
build_flags = 
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1
build_src_filter = +<*.h> +<${PIOENV}/main.cpp>

; Try this first: automatic reconnection
monitor_strategy = latest
; Or if the port hangs:
; monitor_dtr = 0
; monitor_rts = 0

[env:blinker]
lib_deps = adafruit/Adafruit NeoPixel@^1.15.4

[env:wifi]
[env:esp-now-receiver]
lib_deps = knolleary/PubSubClient@^2.8

[env:esp-now-range]
lib_deps = adafruit/Adafruit NeoPixel@^1.15.4

[env:i2c-scanner]
lib_deps = 	
    adafruit/Adafruit BMP280 Library@^3.0.0
	adafruit/Adafruit AHTX0@^2.0.6
